/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_common.h"
#include "fsl_spi.h"
#include "fsl_ctimer.h"
#include "fsl_clock.h"
#include "fsl_pint.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals_cm33_core0 functional group */
/* BOARD_InitPeripherals_cm33_core0 defines for FLEXCOMM8 */
/* Definition of peripheral ID */
#define FLEXCOMM8_PERIPHERAL ((SPI_Type *)FLEXCOMM8)
/* Definition of the clock source frequency */
#define FLEXCOMM8_CLOCK_SOURCE 32000000UL
/* Definition of peripheral ID */
#define CTIMER1_PERIPHERAL CTIMER1
/* Timer tick frequency in Hz (input frequency of the timer) */
#define CTIMER1_TICK_FREQ 100000UL
/* Timer tick period in ns (input period of the timer) */
#define CTIMER1_TICK_PERIOD 10000UL
/* Definition of PWM period channel. */
#define CTIMER1_PWM_PERIOD_CH kCTIMER_Match_3
/* Definition of PWM period */
#define CTIMER1_PWM_PERIOD 99
/* Definition of channel 0 ID */
#define CTIMER1_PWM_0_CHANNEL kCTIMER_Match_0
/* Definition of channel 0 duty */
#define CTIMER1_PWM_0_DUTY 0
/* CTIMER1 interrupt vector ID (number). */
#define CTIMER1_TIMER_IRQN CTIMER1_IRQn
/* CTIMER1 interrupt vector priority. */
#define CTIMER1_TIMER_IRQ_PRIORITY 1
/* BOARD_InitPeripherals_cm33_core0 defines for PINT */
/* Definition of peripheral ID */
#define PINT_PERIPHERAL ((PINT_Type *) PINT_BASE)
/* PINT interrupt vector ID (number). */
#define PINT_PINT_0_IRQN PIN_INT0_IRQn
/* PINT interrupt vector priority. */
#define PINT_PINT_0_IRQ_PRIORITY 2
/* PINT interrupt vector ID (number). */
#define PINT_PINT_1_IRQN PIN_INT1_IRQn
/* PINT interrupt vector priority. */
#define PINT_PINT_1_IRQ_PRIORITY 2
/* PINT interrupt vector ID (number). */
#define PINT_PINT_2_IRQN PIN_INT2_IRQn
/* PINT interrupt vector priority. */
#define PINT_PINT_2_IRQ_PRIORITY 0
/* Definition of PINT interrupt ID for interrupt 0  */
#define PINT_INT_0 kPINT_PinInt0
/* Definition of PINT interrupt ID for interrupt 1  */
#define PINT_INT_1 kPINT_PinInt1
/* Definition of PINT interrupt ID for interrupt 2  */
#define PINT_INT_2 kPINT_PinInt2

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
extern const spi_master_config_t FLEXCOMM8_config;
extern const ctimer_config_t CTIMER1_config;

/***********************************************************************************************************************
 * Callback functions
 **********************************************************************************************************************/
  /* Single callback function declaration */
extern void int_dc_motor_pwm(uint32_t flags);
extern ctimer_callback_t CTIMER1_callback[];
/* INT_0 callback function for the PINT component */
extern void int_enc_inc_clk(pint_pin_int_t pintr, uint32_t pmatch_status);
/* INT_1 callback function for the PINT component */
extern void int_enc_inc_sw(pint_pin_int_t pintr, uint32_t pmatch_status);
/* INT_2 callback function for the PINT component */
extern void int_dc_motor_clk(pint_pin_int_t pintr, uint32_t pmatch_status);

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/

void BOARD_InitPeripherals_cm33_core0(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
